name: Top
version: '${project.version}'
main: net.danh.top.Top
api-version: 1.13
softdepend:
  - Vault
  - PlaceholderAPI
  - MythicMobs
  - PvPManager
authors: [ VoChiDanh ]
commands:
  top:
  danhnhau:

